## Práctico 4: Eight Puzzle

In [ ]:
from eight_puzzle import EightPuzzle
from model import Model

env = EightPuzzle()

In [2]:
obs = env.reset()
print("State:", obs)
print(obs.reshape(3, 3))

print("Action space:",env.action_space)
print("Random action:", env.action_space.sample())

State: [7 4 5 1 3 6 0 2 8]
[[7 4 5]
 [1 3 6]
 [0 2 8]]
Action space: Discrete(4)
Random action: 3


In [5]:
from model import Model

model = Model()
model.get_next_state(obs.reshape(3,3), 1) #Example: Obtaining the resulting state after applying action "Right"
print(model.graph)

{'[[3 0 6]\n [2 4 1]\n [7 8 5]]': {1: array([[3, 6, 0],
       [2, 4, 1],
       [7, 8, 5]])}}


### Random Agent

Possible actions: Up=0, Right=1, Down=2, Left=3


In [4]:
start_state_flatten = env.reset()
done = False
step_counter = 0
all_rewards = 0
env.render()

while not done:
    action = env.action_space.sample()
    obs, reward, done_env, _ = env.step(action)
    all_rewards += reward
    done = done_env
    env.render()
    step_counter += 1
    if (step_counter == 25):  #Early stopping
        done = True

print("Finished in", step_counter, "steps")

3| |4
2|1|8
7|5|6

3|4| 
2|1|8
7|5|6
Action: R

3|4| 
2|1|8
7|5|6
Action: U

3|4| 
2|1|8
7|5|6
Action: U

3|4| 
2|1|8
7|5|6
Action: R

3| |4
2|1|8
7|5|6
Action: L

3|1|4
2| |8
7|5|6
Action: D

3|1|4
2|8| 
7|5|6
Action: R

3|1|4
2|8|6
7|5| 
Action: D

3|1|4
2|8|6
7| |5
Action: L

3|1|4
2|8|6
 |7|5
Action: L

3|1|4
 |8|6
2|7|5
Action: U

 |1|4
3|8|6
2|7|5
Action: U

3|1|4
 |8|6
2|7|5
Action: D

3|1|4
2|8|6
 |7|5
Action: D

3|1|4
2|8|6
7| |5
Action: R

3|1|4
2| |6
7|8|5
Action: U

3|1|4
2|8|6
7| |5
Action: D

3|1|4
2| |6
7|8|5
Action: U

3| |4
2|1|6
7|8|5
Action: U

3|4| 
2|1|6
7|8|5
Action: R

3|4|6
2|1| 
7|8|5
Action: D

3|4|6
2|1|5
7|8| 
Action: D

3|4|6
2|1| 
7|8|5
Action: U

3|4|6
2| |1
7|8|5
Action: L

3| |6
2|4|1
7|8|5
Action: U

Finished in 25 steps


### Ejecución de A*

In [1]:
from eight_puzzle import EightPuzzle
from model import Model

env = EightPuzzle()
obs = env.reset()

# Ejecucion del A*

from a_star_agent import AStarAgent
from model import Model

model = Model()
agent = AStarAgent(model)

print(model.graph)
_, steps = agent.loop(env)  #Complete a_star_agent

{}
6|2|8
3|7|4
1| |5

6|2|8
3| |4
1|7|5
Action: U

6|2|8
 |3|4
1|7|5
Action: L

6|2|8
1|3|4
 |7|5
Action: D

6|2|8
1|3|4
7| |5
Action: R

6|2|8
1| |4
7|3|5
Action: U

6|2|8
1|4| 
7|3|5
Action: R

6|2| 
1|4|8
7|3|5
Action: U

6| |2
1|4|8
7|3|5
Action: L

 |6|2
1|4|8
7|3|5
Action: L

1|6|2
 |4|8
7|3|5
Action: D

1|6|2
4| |8
7|3|5
Action: R

1|6|2
4|3|8
7| |5
Action: D

1|6|2
4|3|8
7|5| 
Action: R

1|6|2
4|3| 
7|5|8
Action: U

1|6|2
4| |3
7|5|8
Action: L

1| |2
4|6|3
7|5|8
Action: U

1|2| 
4|6|3
7|5|8
Action: R

1|2|3
4|6| 
7|5|8
Action: D

1|2|3
4| |6
7|5|8
Action: L

1|2|3
4|5|6
7| |8
Action: D

1|2|3
4|5|6
7|8| 
Action: R



### Cantidad de pasos

In [ ]:
print("Total steps: ", steps)