## Práctico 4: Eight Puzzle

In [1]:
from eight_puzzle import EightPuzzle
from model import Model

env = EightPuzzle()

In [2]:
obs = env.reset()
print("State:", obs)
print(obs.reshape(3, 3))

print("Action space:",env.action_space)
print("Random action:", env.action_space.sample())

State: [0 7 8 1 4 6 5 3 2]
[[0 7 8]
 [1 4 6]
 [5 3 2]]
Action space: Discrete(4)
Random action: 1


In [3]:
from model import Model

model = Model()
model.get_next_state(obs.reshape(3,3), 1) #Example: Obtaining the resulting state after applying action "Right"
print(model.graph)

{'[[0 7 8]\n [1 4 6]\n [5 3 2]]': {1: array([[7, 0, 8],
       [1, 4, 6],
       [5, 3, 2]])}}


### Random Agent

Possible actions: Up=0, Right=1, Down=2, Left=3


In [4]:
start_state_flatten = env.reset()
done = False
step_counter = 0
all_rewards = 0
env.render()

while not done:
    action = env.action_space.sample()
    obs, reward, done_env, _ = env.step(action)
    all_rewards += reward
    done = done_env
    env.render()
    step_counter += 1
    if (step_counter == 25):  #Early stopping
        done = True

print("Finished in", step_counter, "steps")

2|8|4
1|6| 
5|3|7

2|8| 
1|6|4
5|3|7
Action: U

2| |8
1|6|4
5|3|7
Action: L

 |2|8
1|6|4
5|3|7
Action: L

1|2|8
 |6|4
5|3|7
Action: D

1|2|8
5|6|4
 |3|7
Action: D

1|2|8
5|6|4
 |3|7
Action: L

1|2|8
5|6|4
 |3|7
Action: L

1|2|8
5|6|4
 |3|7
Action: L

1|2|8
 |6|4
5|3|7
Action: U

 |2|8
1|6|4
5|3|7
Action: U

 |2|8
1|6|4
5|3|7
Action: L

 |2|8
1|6|4
5|3|7
Action: L

1|2|8
 |6|4
5|3|7
Action: D

1|2|8
 |6|4
5|3|7
Action: L

1|2|8
 |6|4
5|3|7
Action: L

1|2|8
6| |4
5|3|7
Action: R

1|2|8
 |6|4
5|3|7
Action: L

 |2|8
1|6|4
5|3|7
Action: U

2| |8
1|6|4
5|3|7
Action: R

2|6|8
1| |4
5|3|7
Action: D

2|6|8
1|3|4
5| |7
Action: D

2|6|8
1|3|4
 |5|7
Action: L

2|6|8
1|3|4
 |5|7
Action: L

2|6|8
1|3|4
 |5|7
Action: D

2|6|8
1|3|4
5| |7
Action: R

Finished in 25 steps


### Ejecución de A*

In [5]:
from a_star_agent import AStarAgent
from model import Model

model = Model()
agent = AStarAgent(model)

print(model.graph)
_, steps = agent.loop(env)  #Complete a_star_agent

{}
2|6| 
4|8|3
1|5|7
Action: R

2| |6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3
1|5|7
Action: L

 |2|6
4|8|3

KeyboardInterrupt: 

### Cantidad de pasos

In [ ]:
print("Total steps: ", steps)